stages:
  - build

variables:
  BIN_NAME: ping-webhook-bot
  ARTIFACTS_DIR: artifacts
  GO_PROJECT: gitlab.com/ping-webhook-bot

before_script:
  - mkdir -p ${GOPATH}/src/${GO_PROJECT}
  - mkdir -p ${CI_PROJECT_DIR}/${ARTIFACTS_DIR}
  - cp -r ${CI_PROJECT_DIR}/* ${GOPATH}/src/${GO_PROJECT}/

build:
  stage: build
  image: golang:1.9
    
  script:
    - go get -v ${GOPATH}/src/${GO_PROJECT}/...
    - go build -v -o ${ARTIFACTS_DIR}/${BIN_NAME} ${GO_PROJECT}
  
  artifacts:
    name: ${BIN_NAME}-build
    paths:
      - ${ARTIFACTS_DIR}
    expire_in: 1 week
